<a href="https://colab.research.google.com/github/vishalmahor886/NLP_Practical/blob/main/Word_Embedding_Techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [ ]:
## vocabulary_size
voc_size = 10000

#One Hot Representation

In [ ]:
onehot_rep = [one_hot(words, voc_size) for words in sent]
print(onehot_rep)

[[7547, 4878, 5211, 6320], [7547, 4878, 5211, 600], [7547, 6826, 5211, 2079], [5972, 4867, 5735, 984, 3439], [5972, 4867, 5735, 984, 7049], [8869, 7547, 2018, 5211, 9459], [2648, 2900, 6166, 984]]


#Word Embedding Representation

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
import numpy as np

In [ ]:


sent_length = 8
embedded_docs = pad_sequences(onehot_rep, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[    0     0   209   744 17420  9249 19336   998]
 [    0     0 14150 19594 17420  6061 10203 16507]
 [    0     0     0     0  3328   118  1826 13389]
 [    0     0   209 14554 17420  4126   209 19149]
 [    0  4982 12744  7540 17420  6061 10203 16507]
 [    0     0 11239 17420  6061 10203  4667  5821]]


In [ ]:
##10 feature dimentional
dim = 10


In [ ]:
model = Sequential()
model.add(Embedding(voc_size, 10, input_length=sent_length))
model.compile('adam', 'mse')

In [ ]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.predict(embedded_docs)[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step


array([[-0.0051862 , -0.04837788,  0.0372122 , -0.00797714,  0.03575796,
         0.03219848, -0.02922654, -0.00081993,  0.03335519,  0.00435312],
       [-0.0051862 , -0.04837788,  0.0372122 , -0.00797714,  0.03575796,
         0.03219848, -0.02922654, -0.00081993,  0.03335519,  0.00435312],
       [-0.0051862 , -0.04837788,  0.0372122 , -0.00797714,  0.03575796,
         0.03219848, -0.02922654, -0.00081993,  0.03335519,  0.00435312],
       [-0.0051862 , -0.04837788,  0.0372122 , -0.00797714,  0.03575796,
         0.03219848, -0.02922654, -0.00081993,  0.03335519,  0.00435312],
       [-0.02426922, -0.0300179 , -0.01650059,  0.0310861 , -0.02451631,
        -0.01565949,  0.01688631, -0.01176119,  0.03277086,  0.03636015],
       [ 0.0302081 ,  0.03819505, -0.0320845 ,  0.03012026, -0.01347858,
         0.02032372,  0.02195844,  0.03605229, -0.02732207,  0.04060197],
       [ 0.04656917,  0.03912127, -0.04993547, -0.04094502,  0.01361534,
         0.01949662,  0.00879285, -0.01466691

In [ ]:
### another
sent = [
    "The world is a better place",
    "Marvel series is my favourite movie",
    "I like DC movies",
    "the cat is eating the food",
    "Tom and Jerry is my favourite movie",
    "Python is my favourite programming language"
]

In [ ]:
#one hot encoding
vec_size=20000
from tensorflow.keras.preprocessing.text import one_hot
onehot_rep = [one_hot(word, vec_size) for word in sent]
print(onehot_rep)

[[209, 744, 17420, 9249, 19336, 998], [14150, 19594, 17420, 6061, 10203, 16507], [3328, 118, 1826, 13389], [209, 14554, 17420, 4126, 209, 19149], [4982, 12744, 7540, 17420, 6061, 10203, 16507], [11239, 17420, 6061, 10203, 4667, 5821]]


In [ ]:
## Word Embadding layer
dim = 20  ## feature dimention
sent_length = 10
embedded_docs = pad_sequences(onehot_rep, padding='post', maxlen=sent_length)
print(embedded_docs)

[[  209   744 17420  9249 19336   998     0     0     0     0]
 [14150 19594 17420  6061 10203 16507     0     0     0     0]
 [ 3328   118  1826 13389     0     0     0     0     0     0]
 [  209 14554 17420  4126   209 19149     0     0     0     0]
 [ 4982 12744  7540 17420  6061 10203 16507     0     0     0]
 [11239 17420  6061 10203  4667  5821     0     0     0     0]]


In [ ]:
model =Sequential()
model.add(Embedding(voc_size, 10, input_length=sent_length))
model.compile('adam', 'mse')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 258ms/step


array([[[-3.26374397e-02,  4.46949340e-02, -1.73509233e-02,
         -1.05820186e-02, -3.62027176e-02, -2.07211263e-02,
          2.56210454e-02,  4.14708368e-02, -3.55793722e-02,
         -1.43484026e-03],
        [-3.09224613e-02,  3.25818174e-02,  3.32533829e-02,
          3.08522694e-02,  9.95136425e-03,  1.31209157e-02,
         -2.98193451e-02, -2.07009315e-02, -1.26719959e-02,
          3.40427496e-02],
        [ 4.50315587e-02, -4.57668193e-02, -3.38275917e-02,
         -2.50533819e-02,  2.84583494e-03,  1.81698687e-02,
          1.82696320e-02, -2.60169152e-02,  2.40113996e-02,
          4.92980964e-02],
        [-1.04552507e-02, -8.08173418e-03,  9.84824821e-03,
         -3.01388651e-03, -4.81585413e-03,  1.41914375e-02,
          1.95884369e-02, -4.04610038e-02,  1.69534720e-02,
          1.12532154e-02],
        [ 4.50315587e-02, -4.57668193e-02, -3.38275917e-02,
         -2.50533819e-02,  2.84583494e-03,  1.81698687e-02,
          1.82696320e-02, -2.60169152e-02,  2.401139