<a href="https://colab.research.google.com/github/vishalmahor886/NLP_Practical/blob/main/Word2Vec_and_AvgWord2Vec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
import kagglehub
path = kagglehub.dataset_download("uciml/sms-spam-collection-dataset")

Using Colab cache for faster access to the 'sms-spam-collection-dataset' dataset.


In [ ]:
os.listdir(path)

['spam.csv']

In [ ]:
import pandas as pd
messages = pd.read_csv(os.path.join(path,'spam.csv'), encoding='latin')
messages = messages.iloc[:,0:2]

In [ ]:
messages.head()

,v1,v2
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [ ]:
messages = messages.rename(columns={
    'v1':'label',
    'v2':'message'
})

In [ ]:
messages.shape

(5572, 2)

In [ ]:
## data cleaning and preprocessing

import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

nltk.download('stopwords')

ps = PorterStemmer()
stop_words = set(stopwords.words('english'))

corpus = []

for text in messages['message']:
    review = re.sub('[^a-zA-Z]', ' ', text)
    review = review.lower()

    words = review.split()
    words = [ps.stem(word) for word in words if word not in stop_words]

    review = ' '.join(words)
    corpus.append(review)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

In [ ]:
## apply bag of words
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(binary=True, max_features=2500, ngram_range=(2,2))
X=cv.fit_transform(corpus).toarray()

In [ ]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
##encoding using pandas

y = pd.get_dummies(messages['label'], drop_first=True)

In [ ]:
## train test split

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=0)

In [ ]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB()
spam_detect_model.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MultinomialNB()

In [ ]:
y_pred = spam_detect_model.predict(X_test)

In [ ]:
y_pred

array([False, False, False, ..., False, False, False])

In [ ]:
from sklearn.metrics import accuracy_score, classification_report
score = accuracy_score(y_test, y_pred)
score

0.9641255605381166

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       False       0.96      1.00      0.98       949
        True       0.99      0.77      0.86       166

    accuracy                           0.96      1115
   macro avg       0.98      0.88      0.92      1115
weighted avg       0.97      0.96      0.96      1115



TF-IDF

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=2500, ngram_range=(2,2))
X=tfidf.fit_transform(corpus).toarray()

In [ ]:
X


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=0)

In [ ]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB()
spam_detect_model.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


MultinomialNB()

In [ ]:
y_pred = spam_detect_model.predict(X_test)

In [ ]:
##accuracy
score = accuracy_score(y_test, y_pred)
score

0.9426008968609866

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       False       0.94      1.00      0.97       949
        True       0.99      0.62      0.76       166

    accuracy                           0.94      1115
   macro avg       0.96      0.81      0.87      1115
weighted avg       0.95      0.94      0.94      1115



In [ ]:
## Random fores

from sklearn.ensemble import RandomForestClassifier
spam_detect_model = RandomForestClassifier()
spam_detect_model.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


RandomForestClassifier()

In [ ]:
y_pred = spam_detect_model.predict(X_test)

In [ ]:
score = accuracy_score(y_test, y_pred)
score

0.9650224215246637

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

       False       0.96      1.00      0.98       949
        True       0.98      0.78      0.87       166

    accuracy                           0.97      1115
   macro avg       0.97      0.89      0.92      1115
weighted avg       0.97      0.97      0.96      1115



Word2Vec

In [ ]:
pip install gensim

In [ ]:
import gensim.downloader

In [ ]:
## train word2vec from scratch
tokenized_corpus = [sentence.split() for sentence in corpus]
model = gensim.models.Word2Vec(
    sentences=tokenized_corpus,
    window=10,
    min_count=2
)

In [ ]:
model.wv.index_to_key

['u',
 'call',
 'go',
 'get',
 'ur',
 'gt',
 'lt',
 'come',
 'ok',
 'day',
 'free',
 'know',
 'love',
 'like',
 'time',
 'good',
 'want',
 'got',
 'text',
 'send',
 'txt',
 'need',
 'p',
 'one',
 'today',
 'n',
 'take',
 'see',
 'stop',
 'r',
 'home',
 'think',
 'repli',
 'lor',
 'sorri',
 'k',
 'tell',
 'mobil',
 'still',
 'back',
 'da',
 'make',
 'dont',
 'phone',
 'week',
 'pleas',
 'say',
 'hi',
 'new',
 'later',
 'pl',
 'work',
 'ask',
 'hope',
 'co',
 'msg',
 'miss',
 'min',
 'meet',
 'c',
 'dear',
 'messag',
 'night',
 'wait',
 'happi',
 'well',
 'thing',
 'much',
 'great',
 'claim',
 'give',
 'tri',
 'oh',
 'wat',
 'hey',
 'number',
 'b',
 'thank',
 'friend',
 'way',
 'ye',
 'www',
 'e',
 'let',
 'prize',
 'feel',
 'right',
 'tomorrow',
 'even',
 'pick',
 'alreadi',
 'win',
 'tone',
 'cash',
 'said',
 'leav',
 'yeah',
 'care',
 'im',
 'amp',
 'realli',
 'babe',
 'find',
 'morn',
 'life',
 'sleep',
 'last',
 'servic',
 'year',
 'uk',
 'keep',
 'nokia',
 'sure',
 'would',
 'buy',

In [ ]:
model.corpus_count

5572

In [ ]:
model.epochs

5

In [ ]:
model.wv.similar_by_word('hope')

[('day', 0.9998279213905334),
 ('night', 0.9997714757919312),
 ('good', 0.9997543692588806),
 ('feel', 0.9997535347938538),
 ('love', 0.9997519850730896),
 ('well', 0.9997262358665466),
 ('much', 0.9997106194496155),
 ('realli', 0.9997019171714783),
 ('life', 0.9996917247772217),
 ('babe', 0.9996835589408875)]

In [ ]:
## avgword2vec
import numpy as np

def avg_word2vec(doc):
  return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key], axis=0)


In [ ]:
pip install tqdm

In [ ]:
from tqdm import tqdm

In [ ]:
tokenized_corpus

[['go',
  'jurong',
  'point',
  'crazi',
  'avail',
  'bugi',
  'n',
  'great',
  'world',
  'la',
  'e',
  'buffet',
  'cine',
  'got',
  'amor',
  'wat'],
 ['ok', 'lar', 'joke', 'wif', 'u', 'oni'],
 ['free',
  'entri',
  'wkli',
  'comp',
  'win',
  'fa',
  'cup',
  'final',
  'tkt',
  'st',
  'may',
  'text',
  'fa',
  'receiv',
  'entri',
  'question',
  'std',
  'txt',
  'rate',
  'c',
  'appli'],
 ['u', 'dun', 'say', 'earli', 'hor', 'u', 'c', 'alreadi', 'say'],
 ['nah', 'think', 'goe', 'usf', 'live', 'around', 'though'],
 ['freemsg',
  'hey',
  'darl',
  'week',
  'word',
  'back',
  'like',
  'fun',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chg',
  'send',
  'rcv'],
 ['even', 'brother', 'like', 'speak', 'treat', 'like', 'aid', 'patent'],
 ['per',
  'request',
  'mell',
  'mell',
  'oru',
  'minnaminungint',
  'nurungu',
  'vettam',
  'set',
  'callertun',
  'caller',
  'press',
  'copi',
  'friend',
  'callertun'],
 ['winner',
  'valu',
  'network',
  'custom',
  'select'

In [ ]:
from tqdm import tqdm

X = []
for i in tqdm(range(len(tokenized_corpus))):
    X.append(avg_word2vec(tokenized_corpus[i]))

  0%|          | 0/5572 [00:00<?, ?it/s]/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:3596: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:138: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
100%|██████████| 5572/5572 [00:00<00:00, 6725.69it/s]


In [ ]:
type(X)

list

In [ ]:
X[0]

array([-0.24418283,  0.41198713,  0.15276025,  0.06275867,  0.05256109,
       -0.66456944,  0.16009404,  0.7537708 , -0.30647007, -0.1993982 ,
       -0.25618452, -0.4429082 , -0.15383959,  0.18214451,  0.20264499,
       -0.20801134, -0.01162448, -0.4438096 , -0.08094033, -0.6712786 ,
        0.19475698,  0.14652607,  0.17638795, -0.15375341, -0.18186584,
        0.04239184, -0.2766877 , -0.3399649 , -0.32081565,  0.06562144,
        0.48881844,  0.008028  ,  0.18026416, -0.19916046, -0.06607952,
        0.423562  ,  0.02153006, -0.1951975 , -0.16998729, -0.7501574 ,
        0.03583107, -0.33322117, -0.30247506,  0.10113575,  0.17986521,
       -0.1556406 , -0.33245513,  0.02301206,  0.23994471,  0.12339906,
        0.129956  , -0.2658609 , -0.12792014, -0.09197427, -0.24565466,
        0.23998983,  0.24857292, -0.18675697, -0.4859815 ,  0.16093804,
        0.02780226,  0.2281059 , -0.17400421, -0.09832108, -0.48693663,
        0.2423742 ,  0.16061375,  0.33760208, -0.46142158,  0.40

In [ ]:
X[0].shape

(100,)

In [ ]:
tokenized_corpus[1]

['ok', 'lar', 'joke', 'wif', 'u', 'oni']

In [ ]:
X[1]

array([-2.1042460e-01,  3.4909186e-01,  1.3313745e-01,  5.8008295e-02,
        4.2893875e-02, -5.5439532e-01,  1.3589279e-01,  6.3841587e-01,
       -2.6260516e-01, -1.6890211e-01, -2.1099794e-01, -3.7615147e-01,
       -1.3252907e-01,  1.5427069e-01,  1.6971463e-01, -1.7697926e-01,
       -1.1113900e-02, -3.7684211e-01, -7.1892634e-02, -5.6442136e-01,
        1.6414510e-01,  1.2683821e-01,  1.5148102e-01, -1.3415147e-01,
       -1.5367179e-01,  3.8616534e-02, -2.3207088e-01, -2.8529251e-01,
       -2.7418238e-01,  5.1938131e-02,  4.1835380e-01,  2.4124251e-03,
        1.6323744e-01, -1.7489655e-01, -4.7626540e-02,  3.5934040e-01,
        1.9678911e-02, -1.5847732e-01, -1.3999109e-01, -6.3684422e-01,
        2.1194214e-02, -2.7707648e-01, -2.5772974e-01,  8.1038393e-02,
        1.5117759e-01, -1.2730674e-01, -2.8926367e-01,  2.6175531e-02,
        2.0221169e-01,  1.0185969e-01,  1.0829428e-01, -2.1370143e-01,
       -1.0337758e-01, -7.8841992e-02, -1.9726183e-01,  2.0039362e-01,
      

In [ ]:
## train test split

##apply a model